### ISSUE TITLE
Method not allowed with method POST

### ISSUE THREAD

**Issue by gil2gm** [jeremydaly/lambda-api#174]
Hello, i need your help!

I have problem with the api, i use register like this
```
//------------------------------------------------------- index.js
const api = require('lambda-api')({ version: 'v1.0', base: 'v1' });
api.register(require('./routes'), { prefix: '/bot' });
//------------------------------------------------------- 
```

i not have problem with the method get, my problem are the methods POST, i proof the two forms, but any working

```
//------------------------------------------------------- routes.js
module.exports = (api, opts) => {
  api.get('/list', bot.list);
  api.post('/selector', bot.selector);
  api.METHOD('post','/validator_response', bot.validator_response);
  api.post('/hermes', bot.hermes);
};
//-------------------------------------------------------
```

Always i have the same response:
```
Response
{
  "statusCode": 200,
  "headers": {
    "content-type": "application/json"
  },
  "body": "{\"error\":\"Method not allowed\"}"
}
```

**Comment by stawecki** [comment]
Hi Gilberto,
The sample you've provided seems to work fine, when testing sample path `/v1/bot/selector`.
Perhaps the issue is somewhere else.
- Are you sure you're passing the bot.selector/bot.hermes handlers correctly?
- Are you sure you're testing the correct path?
- What are you using for invoking test events?
- Have you also tried printing all the routes with: `api.routes(true);`

Good luck!

**Comment by slootjes** [comment]
It seems I might have a similar issue. I'm using register() on multiple depths, to illustrate it's something like this:

api.js:

```
const api = require('lambda-api')({
    base: '/api'
});

api.register(require('./api/user'), { prefix: '/me' });
```

api/user.js:

```
module.exports = (api, opts) => {
    api.register(require('./user/app'), { prefix: '/apps' });
```

api/user/app.js:

```
module.exports = (api, opts) => {

    api.get(':app/data', async (req, res) => {
        // code
    });

    api.get(':app/data/:scope', async (req, res) => {
        // code
    });

    api.get(':app/data/:scope/:key', async (req, res) => {
        // code
    });

    api.delete(':app/data/user/:key', async (req, res) => {
        // code
    });

    api.put(':app/data', async (req, res) => {
        // code
    });

    api.put(':app/data/user/:key/:value', async (req, res) => {
        // code
    });
}
```

When I do a GET '/api/me/apps/myapp/data/user' which should match the route ':app/data/:scope/:key' however it generated this error:

MethodError: Method not allowed
    at REQUEST.parseRequest (/var/task/node_modules/lambda-api/lib/request.js:247:13)
    at API.run (/var/task/node_modules/lambda-api/index.js:220:21)
    at Runtime.module.exports.handle [as handler] (/var/task/functions/controller/api.js:17:22)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25) {
  method: 'GET',
  path: '/api/me/apps/myapp/data/user'
}

When rendering a full list of routes, this is returned:

```
╟──────────┼─────────────────────────────────────────────────────────────────────────╢
║  PUT     │  /api/me/apps/:app/data                                                 ║
╟──────────┼─────────────────────────────────────────────────────────────────────────╢
║  GET     │  /api/me/apps/:app/data                                                 ║
╟──────────┼─────────────────────────────────────────────────────────────────────────╢
║  DELETE  │  /api/me/apps/:app/data/user/:key                                       ║
╟──────────┼─────────────────────────────────────────────────────────────────────────╢
║  PUT     │  /api/me/apps/:app/data/user/:key/:value                                ║
╟──────────┼─────────────────────────────────────────────────────────────────────────╢
║  GET     │  /api/me/apps/:app/data/:scope                                          ║
╟──────────┼─────────────────────────────────────────────────────────────────────────╢
║  GET     │  /api/me/apps/:app/data/:scope/:key                                     ║
╟──────────┼─────────────────────────────────────────────────────────────────────────╢
```

So I'd say it should work just fine however it doesn't. However when I remove the "DELETE" and "PUT" methods from code, the GET route starts working. So it seems like the matching doesn't fully work when using nested routes.

**Comment by gil2gm** [comment]
I found the problem, lambda-api not working with version 2.0 of api-gateway

```
request.js
 // Set the method
    this.method = this.app._event.httpMethod ? this.app._event.httpMethod.toUpperCase() : 'GET'
```

api-gateway aws v1.0
```
{
  version: '1.0',
  httpMethod: 'POST',
```

api-gateway aws v2.0
```
{
  "version": "2.0",
  "requestContext": {
    "http": {
      "method": "POST",
```

Solution 1: configure api gateway aws with the version 1.0 or
Solution 2: temporal, set in handler function
```
if(event.version === "2.0"){
   event.httpMethod = event.requestContext.http.method;
  }
```

**Comment by jeremydaly** [comment]
v0.11 supports Payload V2 and should be available shortly.

**Comment by capndave** [comment]
@jeremydaly we're unable to `POST` (and perhaps to put?) when running locally using Node 16, but Node 14 works fine. Is that consistent with the Payload V2 thing? Could our failure be related to the type of payload?

**Comment by jeremydaly** [comment]
Strange the Node version would be causing a problem unless it has something to do with the `body` parser. Shouldn't have anything to do with the payload format.
